# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: febc4fd6a6dc9cfffe4ade3ac56c8ba83be8177ed3bf82538d6eed923704d5d7c5384b959c02786ba9cb3ff7cb78a4f4ca0934a6c5c8a3b152ff9cc7ba3abe31

test:
  secret_key_base: 40166ae5b57605fb5a6cfdf066ca85e18c452c5434825b0f5ee3a3523efd2b2a735766f656f540fbbd805e221fe02e61cd16a0a49e820447901a0f7474b2e89b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
